// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDPZGjo9QbGnQsPWczX37pNk5OTafrDAw',
    appId: '1:517514981143:web:111bf11b9d4bff9ee19152',
    messagingSenderId: '517514981143',
    projectId: 'portfolio-75e00',
    authDomain: 'portfolio-75e00.firebaseapp.com',
    storageBucket: 'portfolio-75e00.firebasestorage.app',
    measurementId: 'G-1TE2DQL60W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhDnhHY85PzY8YLTQJqJZaShP8-grsWDY',
    appId: '1:517514981143:android:e247e9a5321a9e7ee19152',
    messagingSenderId: '517514981143',
    projectId: 'portfolio-75e00',
    storageBucket: 'portfolio-75e00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4PrQ4Bl1HznA-ZshcU_dnidVLz7zNTgk',
    appId: '1:517514981143:ios:6c5375e71d22f656e19152',
    messagingSenderId: '517514981143',
    projectId: 'portfolio-75e00',
    storageBucket: 'portfolio-75e00.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4PrQ4Bl1HznA-ZshcU_dnidVLz7zNTgk',
    appId: '1:517514981143:ios:6c5375e71d22f656e19152',
    messagingSenderId: '517514981143',
    projectId: 'portfolio-75e00',
    storageBucket: 'portfolio-75e00.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDPZGjo9QbGnQsPWczX37pNk5OTafrDAw',
    appId: '1:517514981143:web:19e7ba5498c03a10e19152',
    messagingSenderId: '517514981143',
    projectId: 'portfolio-75e00',
    authDomain: 'portfolio-75e00.firebaseapp.com',
    storageBucket: 'portfolio-75e00.firebasestorage.app',
    measurementId: 'G-FSHHBVXV37',
  );
}
